# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

dist: trusty
language: rust
services: docker
sudo: true

env:
  global:
    - CRATE_NAME=vips-sys

matrix:
  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly

addons:
  apt:
    packages:
      - libvips-dev

before_install:
  - set -e
  - rustup self update

install:
  - source ~/.cargo/env || true

script:
  - bash ci/script.sh
  - cargo doc && echo "<meta http-equiv=refresh content=0;url=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`/index.html>" > target/doc/index.html

after_script: set +e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: wqV8Y24Ht7aFYMiiVtb3IkbDq9V6NuqR2EbRSW9FfbsQKxEhi5cXXUFnGKOHcBw5ttQaek8C0ny9A0GeWRnQXYuqldY8lJCYN2Xr+bZdLMWsDhVZK1vamVO0cLND1MDDbNnkZ1VVcJ273ILM/9W0Tejyps10FZXf/2sZEK1rS/K97Dh2xxqstPibc/sXc92E0WBmEPio5SDZeQ3RDKQCmtt8wMGZ/KzxqpsH0rEe/k9isIuvqNzcQHFHHi1epiLnJAFyMTC4XAHRST52i1Xe+AYaQSnLpxtHG00OyHYsho9iA7h2ur3EgS4YzfwhCGgdjQ6UYdcbWq293I/r1l7Pl1dM/YeiDq2T6t0cFLBD86VAeurto1vRM0nX+EbLWZE4Ptx63LlnWa5lRMc6Y7PSm9TczuCzUWUP8pB5YBownQ2Tj8P5mJiGr92Kbbe9cvEdCrAiM1bN3q8l0rE1UD+wOiD8OVAHL329+gPRAFd+k+Ei5/Yeszj52u1KEStZlrq06eGBu8iaxjNoMVRhuP6ZgsbTJwh2Dnf3rh41fRsZyAwH9Md5Y6ylnWmWT7vsPyjRX6n7FrR9//QKmW8pguE7beBi0zbGIP4gPmLFW0f9eNDocbmoGjCS0TvF33NuD/aaYKXc6NSCS7Dwy7dUt2eN69mGVYk99VvcBL1Ell5EqVA=
  keep_history: true
  local_dir: target/doc
  on:
    branch: master

cache: cargo
before_cache:
  # Travis can't cache files that are not readable by "others"
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    # release tags
    - /^v\d+\.\d+\.\d+.*$/
    - master

notifications:
  email:
    on_success: never