language: rust
dist: xenial

matrix:
  include:
    - os: linux
      env: IS_MAIN_BUILD=1
      rust: stable
    - os: linux
      rust: nightly
    - os: osx
      rust: stable
  allow_failures:
    - os: windows
      rust: stable


addons:
  apt:
    packages:
      - libvips-dev

before_install:
  - set -e
  - rustup self update

install:
  - source ~/.cargo/env
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install vips > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install pkg-config > /dev/null; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export PATH="/usr/local/bin:$PATH" fi

script:
  - cargo clean
  - RUSTFLAGS=-Awarnings cargo build
  - RUSTFLAGS=-Awarnings cargo test
  - |
    [ -n "$IS_MAIN_BUILD" ] && RUSTDOCFLAGS=-Awarnings cargo doc && echo "<meta http-equiv=refresh content=0;url=`echo vips_sys | cut -d '/' -f 2`/index.html>" > target/doc/index.html || :


after_script: set +e

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $gh
  keep_history: true
  local_dir: target/doc
  on:
    branch: master
    os: linux
    rust: nightly

cache: cargo
before_cache: |
  chmod -R a+r $HOME/.cargo
  # colon make sure this evalues to true
  [ -n "${IS_MAIN_BUILD}" ] && RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo install --quiet cargo-tarpaulin -f || :


after_success: |
  if [ -n "${IS_MAIN_BUILD}" ]; then
    RUSTFLAGS=-Awarnings taskset -c 0 cargo tarpaulin --out Xml  # limit parallelism to 1, tarpaulin #190
    bash <(curl -s https://codecov.io/bash)
  fi


notifications:
  email:
    on_success: never
